var name1 = prompt ("Pick a name");
var name2 = prompt ("Pick a best friend's name");
var name3 = prompt ("Pick a random name");
var noun1 = prompt ("Pick a noun");;
var noun2 = prompt ("Pick a noun");;
var noun3 = prompt ("Pick a noun");;
var verb1 = prompt ("Pick a fun verb");
var verb2 = prompt ("Pick a different fun verb");
var verb3 = prompt ("Pick a verb");
var adj1 = prompt ("Pick a adjective");
var adj2 = prompt ("Pick a adjective");
var adj3 = prompt ("Pick a adjective");
var adv1 = prompt ("Pick a adverb");
var adv2 = prompt ("Pick a adverb");
var adv3 = prompt ("Pick a adverb");
var prep1 = prompt ("Pick a time of day");
var prep2 = prompt ("Pick a prepisition");
var prep3 = prompt ("Pick a prepisition");

document.write("Hello, my name is " + name1+ ". ");
document.write("One day " + name1 + " woke up confused and ");
document.write(name2 + " asked, what's wrong " + name1 + "? ");
document.write("I'm just tired form " + verb1 + " all last " + prep1 + " at the "+ prep2 + ". " );
document.write(name3+" usally stay up all "+prep1+" long "+verb2+" ,so what's different between you and");
document.write("Well I don't even stay up past " + prep3 + " so not even "+name1+" knows. ");
document.write("The " +noun1+"is going to "+adv1+" "+verb3+" at you. ");
document.write("I think " + name1 + " is a " + adv1 + " " + adv2 + " so he should be fine. ");
document.write("You are" + adv1 + " going to have to fake that " + adv1 + " " + adv3 + " man. ");
document.write(name1 + " is looking " + adv1 + " " + adj1 + " " + adj2 + ".");